"""empty message

Revision ID: 051cc953a281
Revises: 5c3ce2d10f26
Create Date: 2023-09-23 16:05:58.026617

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '051cc953a281'
down_revision = '5c3ce2d10f26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character_sheet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('temp_hp', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('defenses', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('conditions', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character_sheet', schema=None) as batch_op:
        batch_op.drop_column('conditions')
        batch_op.drop_column('defenses')
        batch_op.drop_column('temp_hp')

    # ### end Alembic commands ###
