"""empty message

Revision ID: 1c0d5a20a697
Revises: d09ae231199a
Create Date: 2023-09-13 20:47:43.595885

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1c0d5a20a697'
down_revision = 'd09ae231199a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('race', schema=None) as batch_op:
        batch_op.add_column(sa.Column('str_bonus', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('dex_bonus', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('con_bonus', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('int_bonus', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('wis_bonus', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('cha_bonus', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('race', schema=None) as batch_op:
        batch_op.drop_column('cha_bonus')
        batch_op.drop_column('wis_bonus')
        batch_op.drop_column('int_bonus')
        batch_op.drop_column('con_bonus')
        batch_op.drop_column('dex_bonus')
        batch_op.drop_column('str_bonus')

    # ### end Alembic commands ###
