"""empty message

Revision ID: 1cd79e746e0a
Revises: ba95be4977af
Create Date: 2023-09-13 00:53:12.098953

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1cd79e746e0a'
down_revision = 'ba95be4977af'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character_sheet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('race_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'race', ['race_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character_sheet', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('race_id')

    # ### end Alembic commands ###
