"""empty message

Revision ID: 1ffa4d0bee31
Revises: f2731c6a7e50
Create Date: 2023-10-01 19:46:35.298209

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '1ffa4d0bee31'
down_revision = 'f2731c6a7e50'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('campaign_chat_message')
    with op.batch_alter_table('campaign_file', schema=None) as batch_op:
        batch_op.drop_constraint('campaign_file_campaign_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'campaign', ['campaign_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('character_sheet', schema=None) as batch_op:
        batch_op.drop_constraint('character_sheet_campaign_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'campaign', ['campaign_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('invitation', schema=None) as batch_op:
        batch_op.drop_constraint('invitation_campaign_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'campaign', ['campaign_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('invitation', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('invitation_campaign_id_fkey', 'campaign', ['campaign_id'], ['id'])

    with op.batch_alter_table('character_sheet', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('character_sheet_campaign_id_fkey', 'campaign', ['campaign_id'], ['id'])

    with op.batch_alter_table('campaign_file', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('campaign_file_campaign_id_fkey', 'campaign', ['campaign_id'], ['id'])

    op.create_table('campaign_chat_message',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('campaign_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('sender_uid', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('message', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('timestamp', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], name='campaign_chat_message_campaign_id_fkey'),
    sa.ForeignKeyConstraint(['sender_uid'], ['user.uid'], name='campaign_chat_message_sender_uid_fkey'),
    sa.PrimaryKeyConstraint('id', name='campaign_chat_message_pkey')
    )
    # ### end Alembic commands ###
