"""empty message

Revision ID: 3c2f8b2eb0f7
Revises: 4f5ba5b94dbb
Create Date: 2023-09-19 23:49:23.916543

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3c2f8b2eb0f7'
down_revision = '4f5ba5b94dbb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('class_saving_throws')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('class_saving_throws',
    sa.Column('class_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('ability_score_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['ability_score_id'], ['ability_score.id'], name='class_saving_throws_ability_score_id_fkey'),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], name='class_saving_throws_class_id_fkey')
    )
    # ### end Alembic commands ###
