"""empty message

Revision ID: 4f5ba5b94dbb
Revises: 0a68fc7db6bb
Create Date: 2023-09-19 23:29:48.454785

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f5ba5b94dbb'
down_revision = '0a68fc7db6bb'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.add_column(sa.Column('saving_throws', sa.PickleType(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('classes', schema=None) as batch_op:
        batch_op.drop_column('saving_throws')

    # ### end Alembic commands ###
