"""empty message

Revision ID: 57e8f0293c39
Revises: 
Create Date: 2023-09-14 15:17:46.060888

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57e8f0293c39'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ability_score', schema=None) as batch_op:
        batch_op.add_column(sa.Column('full_name', sa.String(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ability_score', schema=None) as batch_op:
        batch_op.drop_column('full_name')

    # ### end Alembic commands ###
