"""empty message

Revision ID: 58f5c97bcf57
Revises: b3b933e4f127
Create Date: 2023-09-20 18:49:20.614267

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '58f5c97bcf57'
down_revision = 'b3b933e4f127'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character_sheet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('alignment', sa.String(length=40), nullable=True))
        batch_op.alter_column('background',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.String(length=40),
               nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character_sheet', schema=None) as batch_op:
        batch_op.alter_column('background',
               existing_type=sa.String(length=40),
               type_=sa.VARCHAR(length=50),
               nullable=False)
        batch_op.drop_column('alignment')

    # ### end Alembic commands ###
