"""empty message

Revision ID: 5c8001020a3b
Revises: 3a9548a6563e
Create Date: 2023-09-16 14:08:19.399624

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5c8001020a3b'
down_revision = '3a9548a6563e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character_sheet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('characterPic', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character_sheet', schema=None) as batch_op:
        batch_op.drop_column('characterPic')

    # ### end Alembic commands ###
