"""empty message

Revision ID: 8593a034f4c4
Revises: bca192157b04
Create Date: 2023-09-22 17:54:59.032652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8593a034f4c4'
down_revision = 'bca192157b04'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('character_skill')
    op.drop_table('skill')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('skill',
    sa.Column('id', sa.INTEGER(), server_default=sa.text("nextval('skill_id_seq'::regclass)"), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(length=80), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name='skill_pkey'),
    postgresql_ignore_search_path=False
    )
    op.create_table('character_skill',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('character_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('skill_id', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('modifier', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character_sheet.id'], name='character_skill_character_id_fkey'),
    sa.ForeignKeyConstraint(['skill_id'], ['skill.id'], name='character_skill_skill_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='character_skill_pkey')
    )
    # ### end Alembic commands ###
