"""empty message

Revision ID: 92132f67f798
Revises: f3e16a52f19f
Create Date: 2023-09-12 21:02:49.326202

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '92132f67f798'
down_revision = 'f3e16a52f19f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('classes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('hit_dice', sa.String(), nullable=True),
    sa.Column('primary_ability', sa.String(), nullable=True),
    sa.Column('saving_throw_proficiencies', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('equipment',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('race',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('character_classes',
    sa.Column('character_id', sa.Integer(), nullable=True),
    sa.Column('class_id', sa.Integer(), nullable=True),
    sa.Column('level', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['character_id'], ['character_sheet.id'], ),
    sa.ForeignKeyConstraint(['class_id'], ['classes.id'], )
    )
    op.create_table('character_equipments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('character_id', sa.Integer(), nullable=False),
    sa.Column('equipment_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['character_id'], ['character_sheet.id'], ),
    sa.ForeignKeyConstraint(['equipment_id'], ['equipment.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('character_sheet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('strength', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('dexterity', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('constitution', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('intelligence', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('wisdom', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('charisma', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character_sheet', schema=None) as batch_op:
        batch_op.drop_column('charisma')
        batch_op.drop_column('wisdom')
        batch_op.drop_column('intelligence')
        batch_op.drop_column('constitution')
        batch_op.drop_column('dexterity')
        batch_op.drop_column('strength')

    op.drop_table('character_equipments')
    op.drop_table('character_classes')
    op.drop_table('race')
    op.drop_table('equipment')
    op.drop_table('classes')
    # ### end Alembic commands ###
