"""empty message

Revision ID: 9b3fd0f6d394
Revises: 1c0d5a20a697
Create Date: 2023-09-13 21:44:39.222807

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9b3fd0f6d394'
down_revision = '1c0d5a20a697'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('language', schema=None) as batch_op:
        batch_op.add_column(sa.Column('description', sa.Text(), nullable=True))

    with op.batch_alter_table('proficiency', schema=None) as batch_op:
        batch_op.add_column(sa.Column('category', sa.String(), nullable=True))

    with op.batch_alter_table('race', schema=None) as batch_op:
        batch_op.drop_column('language_desc')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('race', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language_desc', sa.VARCHAR(), autoincrement=False, nullable=True))

    with op.batch_alter_table('proficiency', schema=None) as batch_op:
        batch_op.drop_column('category')

    with op.batch_alter_table('language', schema=None) as batch_op:
        batch_op.drop_column('description')

    # ### end Alembic commands ###
