"""empty message

Revision ID: bca192157b04
Revises: 58f5c97bcf57
Create Date: 2023-09-20 23:48:14.863132

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bca192157b04'
down_revision = '58f5c97bcf57'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character_ability_values', schema=None) as batch_op:
        batch_op.drop_constraint('character_ability_values_ability_score_id_fkey', type_='foreignkey')
        batch_op.drop_constraint('character_ability_values_character_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'character_sheet', ['character_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'ability_score', ['ability_score_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('character_equipments', schema=None) as batch_op:
        batch_op.drop_constraint('character_equipments_character_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'character_sheet', ['character_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('character_sheet', schema=None) as batch_op:
        batch_op.alter_column('background',
               existing_type=sa.VARCHAR(length=40),
               nullable=False)
        batch_op.alter_column('alignment',
               existing_type=sa.VARCHAR(length=40),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character_sheet', schema=None) as batch_op:
        batch_op.alter_column('alignment',
               existing_type=sa.VARCHAR(length=40),
               nullable=True)
        batch_op.alter_column('background',
               existing_type=sa.VARCHAR(length=40),
               nullable=True)

    with op.batch_alter_table('character_equipments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('character_equipments_character_id_fkey', 'character_sheet', ['character_id'], ['id'])

    with op.batch_alter_table('character_ability_values', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('character_ability_values_character_id_fkey', 'character_sheet', ['character_id'], ['id'])
        batch_op.create_foreign_key('character_ability_values_ability_score_id_fkey', 'ability_score', ['ability_score_id'], ['id'])

    # ### end Alembic commands ###
