"""empty message

Revision ID: d09ae231199a
Revises: 1cd79e746e0a
Create Date: 2023-09-13 00:56:46.146532

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd09ae231199a'
down_revision = '1cd79e746e0a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('subrace')
    with op.batch_alter_table('character_sheet', schema=None) as batch_op:
        batch_op.alter_column('race_id',
               existing_type=sa.INTEGER(),
               nullable=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character_sheet', schema=None) as batch_op:
        batch_op.alter_column('race_id',
               existing_type=sa.INTEGER(),
               nullable=True)

    op.create_table('subrace',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('race_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['race_id'], ['race.id'], name='subrace_race_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='subrace_pkey'),
    sa.UniqueConstraint('name', name='subrace_name_key')
    )
    # ### end Alembic commands ###
