"""empty message

Revision ID: db4553fcbf52
Revises: 1ffa4d0bee31
Create Date: 2023-10-03 19:37:07.209019

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'db4553fcbf52'
down_revision = '1ffa4d0bee31'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character_ability_values', schema=None) as batch_op:
        batch_op.drop_constraint('character_ability_values_ability_score_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'ability_score', ['ability_score_id'], ['id'])

    with op.batch_alter_table('character_sheet', schema=None) as batch_op:
        batch_op.drop_constraint('character_sheet_campaign_id_fkey', type_='foreignkey')
        batch_op.create_foreign_key(None, 'campaign', ['campaign_id'], ['id'], ondelete='SET NULL')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character_sheet', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('character_sheet_campaign_id_fkey', 'campaign', ['campaign_id'], ['id'], ondelete='CASCADE')

    with op.batch_alter_table('character_ability_values', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key('character_ability_values_ability_score_id_fkey', 'ability_score', ['ability_score_id'], ['id'], ondelete='CASCADE')

    # ### end Alembic commands ###
