"""empty message

Revision ID: f2731c6a7e50
Revises: 5c3ce2d10f26
Create Date: 2023-09-29 20:41:39.026326

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f2731c6a7e50'
down_revision = '5c3ce2d10f26'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaign',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('starting_location', sa.String(length=120), nullable=False),
    sa.Column('status', sa.Enum('SCHEDULED', 'ACTIVE', 'COMPLETED', name='campaignstatus'), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('dm_uid', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['dm_uid'], ['user.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campaign_chat_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('sender_uid', sa.String(), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('timestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
    sa.ForeignKeyConstraint(['sender_uid'], ['user.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('campaign_file',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('filename', sa.String(length=255), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('invitation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=False),
    sa.Column('player_uid', sa.String(), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('sent_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaign.id'], ),
    sa.ForeignKeyConstraint(['player_uid'], ['user.uid'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('character_sheet', schema=None) as batch_op:
        batch_op.add_column(sa.Column('temp_hp', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('defenses', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('conditions', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('campaign_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, 'campaign', ['campaign_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('character_sheet', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('campaign_id')
        batch_op.drop_column('conditions')
        batch_op.drop_column('defenses')
        batch_op.drop_column('temp_hp')

    op.drop_table('invitation')
    op.drop_table('campaign_file')
    op.drop_table('campaign_chat_message')
    op.drop_table('campaign')
    # ### end Alembic commands ###
