"""empty message

Revision ID: ff602a4dd58e
Revises: cd5ab476f85d
Create Date: 2023-09-13 22:07:02.194666

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff602a4dd58e'
down_revision = 'cd5ab476f85d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('race_fixed_proficiencies',
    sa.Column('race_id', sa.Integer(), nullable=True),
    sa.Column('proficiency_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['proficiency_id'], ['proficiency.id'], ),
    sa.ForeignKeyConstraint(['race_id'], ['race.id'], )
    )
    op.create_table('race_optional_proficiencies',
    sa.Column('race_id', sa.Integer(), nullable=True),
    sa.Column('proficiency_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['proficiency_id'], ['proficiency.id'], ),
    sa.ForeignKeyConstraint(['race_id'], ['race.id'], )
    )
    op.drop_table('race_proficiencies')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('race_proficiencies',
    sa.Column('race_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('proficiency_id', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['proficiency_id'], ['proficiency.id'], name='race_proficiencies_proficiency_id_fkey'),
    sa.ForeignKeyConstraint(['race_id'], ['race.id'], name='race_proficiencies_race_id_fkey')
    )
    op.drop_table('race_optional_proficiencies')
    op.drop_table('race_fixed_proficiencies')
    # ### end Alembic commands ###
